version: '3.8'

services:
  beckend_rds:
    #image: your-service1-image
    build:
      context: ./Dynamic_services_static_front_project/backend_rds
    ports:
      - "5000:5000"
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
     - project-network

  backend_redis:
    #image: your-service2-image
    build:
      context: ./Dynamic_services_static_front_project/backend_redis
    ports:
      - "5001:5001"
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    # depends_on:
    #  - backend_rds
    networks:
     - project-network
    
  rds_postgres:
    image: postgres:alpine
    ports:
      - "8000:8000"
    networks:
      - project-network

  redis_redis:
    image: redis:alpine
    ports:
      - "8001:8001"
    networks:
      - project-network


  
networks:
  project-network:
    driver: bridge
    # external: true
